---
# Main YAML Function
#
# Setup the OS Tier
- name: setup os tier
  hosts: "frontends,apps,appdbs"
  become: yes
  gather_facts: false
  roles:
    - {name: os-tier, tags: [os-tier]}

# Setup the LBAAS Tier
- name: setup lbaas tier
  hosts: frontends
  become: yes
  gather_facts: false
  roles:
    - {name: lbaas-tier, tags: [haproxy]}

# Setup the APP Tier
- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: app-tier, tags: [tomcat]}

# Setup DB Tier
- name: setup database tier
  become: yes
  hosts: appdbs
  gather_facts: true
  roles:
    - {name: db-tier, tags: [dbs, postgres]}

