---
# Tasks file for roles/lbaas-tier
# Installation of packages for HA Proxy
# Inventory frontends
# Install the application
- name: Install {{ payload }}
  yum:
   name: "{{ payload }}"
   state: latest
# Set the systemctl state of to Enabled
- name: Start {{ payload }}
  service:
    name: "{{ payload }}"
    enabled: yes
# Configure the proxy configuration
- name: Configure lbaas-proxy to load balance to app servers
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
   mode: 0644
  notify:
   - restart_lbaas

